name: Build and release

on: workflow_dispatch

jobs:
  windows-x64-release:
    runs-on: windows-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build and package
        run: |
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-release
          path: |
            src-tauri/target/release/bundle/

  macos-universal-release:
    runs-on: macos-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install npm dependencies
        run: |
          npm install

      - name: Install additional binaries for building MacOS universal release
        run: |
          rustup target add aarch64-apple-darwin

      - name: Build and package
        env:
          CI: true
        run: |
          npm run tauri build --target universal-apple-darwin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-release
          path: |
            src-tauri/target/release/bundle/

  linux-x64-release:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install additional Install npm d for Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build and package
        run: |
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64-release
          path: |
            src-tauri/target/release/bundle/
